name: Code Review Bot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the pull request code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET (if applicable)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Step 3: Run the custom script for code analysis
      - name: Run Code Analysis
        run: |
          dotnet build --configuration Debug
          dotnet format --check  # Example: Check formatting
          echo "Code check complete."

      # Step 4: Add comments to the pull request
      - name: Add PR Comments
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            🛠 Code Check Results:
            - All code was formatted correctly.
            - No issues found in the build.
